<?php

/**
 * @file
 * UI Patterns tests module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\ui_patterns_test\Hook\UiPatternsTestTokensHooks;

/**
 * Implements hook_component_info_alter().
 */
#[LegacyHook]
function ui_patterns_test_component_info_alter(array &$definitions): void {
  Drupal::service(UiPatternsTestTokensHooks::class)->componentInfoAlter($definitions);
}
