<?php

/**
 * @file
 * Contains code of ui_patterns_legacy module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\ui_patterns_legacy\Hook\UiPatternsLegacyHooks;

/**
 * Implements hook_element_info_alter().
 */
#[LegacyHook]
function ui_patterns_legacy_element_info_alter(array &$types): void {
  Drupal::service(UiPatternsLegacyHooks::class)->elementInfoAlter($types);
}
