<?php

/**
 * @file
 * UI Patterns Field Formatters module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\ui_patterns_field_formatters\Hook\UiPatternsFieldFormattersHooks;

/**
 * Implements hook_field_formatter_info_alter().
 *
 * All field types to field formatters with hook_field_formatter_info_alter.
 */
#[LegacyHook]
function ui_patterns_field_formatters_field_formatter_info_alter(array &$info): void {
  Drupal::service(UiPatternsFieldFormattersHooks::class)->fieldFormatterInfoAlter($info);
}
