<?php

/**
 * @file
 * Contains module file.
 */

declare(strict_types=1);

use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\ui_patterns_layouts\Hook\UiPatternsLayoutsHooks;

/**
 * Implements hook_element_info_alter().
 */
#[LegacyHook]
function ui_patterns_layouts_element_info_alter(array &$types): void {
  Drupal::service(UiPatternsLayoutsHooks::class)->elementInfoAlter($types);
}

/**
 * Implements hook_entity_view_alter().
 *
 * Field layout is not adding entity information to the layout.
 * We need to add it in another step.
 */
#[LegacyHook]
function ui_patterns_layouts_entity_view_alter(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display): void {
  Drupal::service(UiPatternsLayoutsHooks::class)->entityViewAlter($build, $entity, $display);
}
