<?php

/**
 * @file
 * Adds UI Patterns themes and UI Elements.
 */

declare(strict_types=1);

use Drupal\Core\Field\FieldConfigInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\ui_patterns\Hook\FieldConfigDelete;
use Drupal\ui_patterns\Hook\UiPatternsHooks;

/**
 * Implements hook_element_info_alter().
 */
#[LegacyHook]
function ui_patterns_element_info_alter(array &$types): void {
  Drupal::service(UiPatternsHooks::class)->elementInfoAlter($types);
}

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
#[LegacyHook]
function ui_patterns_plugin_filter_block__ui_patterns_alter(array &$definitions, array $extra): void {
  Drupal::service(UiPatternsHooks::class)->pluginFilterBlockUiPatternsAlter($definitions, $extra);
}

/**
 * Implements hook_ENTITY_TYPE_delete().
 */
#[LegacyHook]
function ui_patterns_field_config_delete(FieldConfigInterface $field_config): void {
  Drupal::service(FieldConfigDelete::class)->fieldConfigDeleteHook($field_config);
}
