<?php

/**
 * @file
 * Install, update and uninstall functions for ept_core_starterkit.
 */

use Drush\Drush;

/**
 * Implements hook_requirements().
 */
function ept_core_starterkit_requirements($phase) {
  if ($phase != 'install') {
    return [];
  }

  $drush_version = (class_exists('\Drush\Drush')) ? Drush::getMajorVersion() : 8;

  if ($drush_version >= 12) {
    return [];
  }

  return [
    'ept_core_starterkit_drush_version' => [
      'title' => t('Drush 12+ is required'),
      'value' => t('Not created'),
      'description' => t('The EPT Starterkit requires Drush 12+ version.'),
      'severity' => REQUIREMENT_ERROR,
    ],
  ];
}
