<?php

/**
 * @file
 * Contains module file.
 */

declare(strict_types=1);

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\ui_patterns_ui\ComponentFormDisplayInterface;
use Drupal\ui_patterns_ui\Hook\ComponentFormDisplayHooks;
use Drupal\ui_patterns_ui\Hook\ComponentPreBuildAlter;
use Drupal\ui_patterns_ui\Hook\UiPatternsUiHooks;

/**
 * Implements hook_component_form_display_insert().
 */
#[LegacyHook]
function ui_patterns_ui_component_form_display_insert(ComponentFormDisplayInterface $component_form_display): void {
  Drupal::service(ComponentFormDisplayHooks::class)->componentFormDisplayHook($component_form_display);
}

/**
 * Implements hook_patterns_ui_component_form_display_delete().
 */
#[LegacyHook]
function ui_patterns_ui_component_form_display_delete(ComponentFormDisplayInterface $component_form_display): void {
  Drupal::service(ComponentFormDisplayHooks::class)->componentFormDisplayHook($component_form_display);
}

/**
 * Implements hook_patterns_ui_component_form_display_update().
 */
#[LegacyHook]
function ui_patterns_ui_component_form_display_update(ComponentFormDisplayInterface $component_form_display): void {
  Drupal::service(ComponentFormDisplayHooks::class)->componentFormDisplayHook($component_form_display);
}

/**
 * Implements hook_ui_patterns_form_alter().
 */
#[LegacyHook]
function ui_patterns_ui_ui_patterns_form_alter(array &$form, FormStateInterface $form_state): void {
  Drupal::service(UiPatternsUiHooks::class)->uiPatternsFormAlter($form, $form_state);
}

/**
 * Implements hook_config_schema_info_alter().
 */
#[LegacyHook]
function ui_patterns_ui_config_schema_info_alter(array &$definitions): void {
  Drupal::service(UiPatternsUiHooks::class)->configSchemaInfoAlter($definitions);
}

/**
 * Implements hook_ui_patterns_component_pre_build_alter().
 */
#[LegacyHook]
function ui_patterns_ui_ui_patterns_component_pre_build_alter(array &$element): void {
  Drupal::service(ComponentPreBuildAlter::class)->uiPatternsComponentPreBuildAlter($element);
}
