<?php

/**
 * @file
 * UI Patterns Blocks custom add-ons.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\ui_patterns_blocks\Hook\UiPatternsBlocksHooks;

/**
 * Implements hook_plugin_filter_TYPE__CONSUMER_alter().
 */
#[LegacyHook]
function ui_patterns_blocks_plugin_filter_block__layout_builder_alter(array &$definitions, array $extra): void {
  Drupal::service(UiPatternsBlocksHooks::class)->pluginFilterBlockLayoutBuilderAlter($definitions, $extra);
}

/**
 * Implements hook_plugin_filter_TYPE_alter().
 */
#[LegacyHook]
function ui_patterns_blocks_plugin_filter_block_alter(array &$definitions, array $extra, ?string $consumer): void {
  Drupal::service(UiPatternsBlocksHooks::class)->pluginFilterBlockAlter($definitions, $extra, $consumer);
}
