<?php

/**
 * @file
 * Contains code of ui_patterns_library module.
 */

declare(strict_types=1);

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\ui_patterns_library\Hook\UiPatternsLibraryHooks;

/**
 * Implements hook_theme().
 */
#[LegacyHook]
function ui_patterns_library_theme(): array {
  return Drupal::service(UiPatternsLibraryHooks::class)->theme();
}

/**
 * Implements hook_element_info_alter().
 */
#[LegacyHook]
function ui_patterns_library_element_info_alter(array &$types): void {
  Drupal::service(UiPatternsLibraryHooks::class)->elementInfoAlter($types);
}
