<?php

/**
 * @file
 * banner_paragraph.module
 */

/**
 * Implements hook_theme_suggestions_paragraph_alter().
 */
function banner_paragraph_theme_suggestions_paragraph_alter(
  array &$suggestions,
  array $variables
): void {
  /** @var \Drupal\paragraphs\Entity\Paragraph $paragraph */
  $paragraph = $variables['elements']['#paragraph'];
  $suggestions[] = 'paragraph__' . $paragraph->bundle();
}
